export const projects = [
    {
        slug: "books",
        title: "E-Books",
        description: "Streamlining digital reading with a clean interface for organizing and exploring your favorite book collections.",
        tags: ["TailwinCSS", "DaisyUI", "React.js"],
        github: "https://github.com/NuruddinJewel/E-Books",
        live: "https://e-books-list.surge.sh/",
        image: "/images/ebook1.jpg",
        featured: true,
    },
    {
        slug: "calculator",
        title: "Calculator",
        description: "A responsive, user-friendly calculator for everyday math.",
        tags: ["JavaScript", "React.js", "TailwindCSS", "DaisyUI"],
        github: "https://github.com/NuruddinJewel/React_Calculator",
        live: "https://nuruddinjewel.github.io/React_Calculator/",
        image: "/images/calculator.jpg",
        featured: false,
    },
    {
        slug: "weather-app",
        title: "Weather App",
        description: "Real-time weather app using OpenWeather API with search functionality.",
        tags: ["JavaScript", "React.js", "TailwindCSS", "DaisyUI"],
        github: "https://github.com/NuruddinJewel/Weather_App",
        live: " https://nuruddinjewel.github.io/Weather_App/",
        image: "/images/weather.jpg",
        featured: true,
    },
    {
        slug: "language-app",
        title: "English Learning Platform",
        description: "Bridge the language gap with an intuitive app that simplifies English grammar and vocabulary for Bengali natives.",
        tags: ["HTML5", "CSS3", "Tailwind CSS", "DaisyUI", "Javascript(ES6)"],
        github: "https://github.com/NuruddinJewel/Project_English_Janala",
        live: "https://nuruddinjewel.github.io/Project_English_Janala/",
        image: "/images/vocabulary.jpg",
        featured: false,
    },
    {
        slug: "skillsphere",
        title: "SkillSphere – Online Learning Platform",
        description: "Based on our platform's mission, SkillSphere exists to help individuals 'Unlock Your Global Potential: Learn from Experts.' Our primary goal is to provide a premier digital space where students worldwide can connect with industry leaders and master high-demand, new skills.",
        tags: ["Next.js", "DaisyUI", "Tailwind CSS", "HTML5", "CSS3", "React-Icons", "Lucide-React"],
        github: "https://github.com/NuruddinJewel/Assignment-8",
        live: "https://assignment-8-flame.vercel.app/",
        image: "/images/skillsphere1.jpg",
        featured: true,
    },
    {
        slug: "digitools",
        title: "DigiTools – Supercharge Your Digital Workflow",
        description: "DigiTools is a modern digital marketplace to discover, purchase, and instantly access 200+ premium digital tools — all in one place. Built for creators, developers, and teams who move fast.",
        tags: ["React.js", "DaisyUI", "Tailwind CSS"],
        github: "https://github.com/NuruddinJewel/Assignment-6",
        live: "https://nuruddinjewel-assignment-6.netlify.app/",
        image: "/images/digitools.jpg",
        featured: true,
    },
    {
        slug: "cricket",
        title: "Cricket Squad Manager",
        description: "A web application designed for cricket enthusiasts to manage a virtual team with seamless player buying and squad-cleaning functionalities.",
        tags: ["React.js", "DaisyUI", "Tailwind CSS"],
        github: "https://github.com/NuruddinJewel/Cricket_Game",
        live: "https://nuruddinjewel.github.io/Cricket_Game/",
        image: "/images/dreamteam.jpg",
        featured: false,
    },
    {
        slug: "job_application",
        title: "Job Application Tracker",
        description: "A modern web application to track and manage job applications effectively. It provides a centralized dashboard to monitor key metrics like total jobs applied, upcoming interviews, and rejections in a visually organized way.",
        tags: ["Javascript(ES6)", "Tailwind CSS", "HTML5", "CSS3"],
        github: "https://github.com/NuruddinJewel/Assignment-4",
        live: "https://nuruddinjewel.github.io/Assignment-4/",
        image: "/images/jobs1.jpg",
        featured: false,
    },
    {
        slug: "githubissues",
        title: "Track and Manage Project Issues",
        description: "A centralized issue tracking system designed to streamline project workflows by logging, monitoring, and resolving bugs efficiently. It features a modern dashboard to categorize issues by status, priority, and team assignments.",
        tags: ["Javascript(ES6)", "Tailwind CSS", "HTML5", "CSS3"],
        github: "https://github.com/NuruddinJewel/Assignment-5",
        live: "https://nuruddinjewel.github.io/Assignment-5/",
        image: "/images/issues.jpg",
        featured: true,
    },
    {
        slug: "game",
        title: "NeonSnake Pro",
        description: "A sleek, neon-themed Snake game featuring responsive design, high-score tracking, and fluid animations powered by React state management.",
        tags: ["DaisyUI", "Tailwind CSS", "React.js", "HTML5", "CSS3"],
        github: "https://github.com/NuruddinJewel/react-snake-game",
        live: "https://react-snake-game1.netlify.app/",
        image: "/images/game1.jpg",
        featured: false,
    },
]

export function getProjectBySlug(slug) {
    return projects.find((p) => p.slug === slug)
}

export function getFeaturedProjects() {
    return projects.filter((p) => p.featured)
}